---
version: "1"

env: "development"
endpoint: "tcp://*:9797"
client-endpoint: "tcp://localhost:9797"
heartbeat-liveness: 3
heartbeat-interval: 2500000

log:
  formatter: "text"
  level: "info"

buses:
  - name: state
    frontend: "@tcp://127.0.0.1:11000"
    backend: "@tcp://127.0.0.1:11001"
    capture: "inproc://broker.state.pipe"
  - name: event
    frontend: "@tcp://127.0.0.1:12000"
    backend: "@tcp://127.0.0.1:12001"
    capture: "inproc://broker.event.pipe"
  - name: metric
    frontend: "@tcp://127.0.0.1:13000"
    backend: "@tcp://127.0.0.1:13001"
    capture: "inproc://broker.metric.pipe"
